### PR TITLE
T026 Meet The Team Section

### PR DESCRIPTION
**Pull request by lia-arroyo**
Hi! Here is the code for the Meet The Team section. 

Preview:
image

I still need to add the title underneath each team member. Some delays are observed relating to loading the images.

### CODE REVIEW

**Review by KennethZhu904 — APPROVED** [review]
Clean code, nicely done. LGTM!

**Review by KennethZhu904 — CHANGES_REQUESTED** [review]
Hey Lia, just have a looked again and realised that images on my big screen are too big. Just make sure it is adjustable on big screens. I have sent through the Loom video on what i meant.

**Review by KennethZhu904 — APPROVED** [review]
LGTM

**Comment by lia-arroyo** [comment]
Hello! FYI I have just added titles to match our Figma designs. :)

**Review by KennethZhu904 — APPROVED** [review]
LGTM!

**Pull request merged**
